enum AppText {
  titleEcosystem,
  titleLoginSlogan,
  titleEmail,
  titlePassword,
  titleConfirmDelete,
  titleSearch,
  titleName,
  titlePosition,
  titlePhone,
  titleIdStaff,
  titleDepartments,
  titleGender,
  titleCodeUser,
  titleBirthDay,
  titleDetailedInformation,
  titleAddress,
  titleMajor,
  titleWorkType,
  titleStatus,
  titleLeader,
  titleOwner,
  titleEmployeeInformation,
  titlePrivateInformation,
  titleNote,
  titlePrivateNote,
  titleInternalAccount,
  titleEmailLogin,
  titleRole,
  titleAddAccount,
  titleAddAccountFailed,
  titleLackOfInformation,
  titleChangePassword,
  titleReEnterPassword,
  titleNewPassword,
  titleOldPassword,
  titleChangePasswordSuccess,
  titleChangePasswordFailed,
  titleUserInformation,
  titleUpdateUserSuccess,
  titleUpdateUserFailed,
  titleDeleteSuccess,
  titleDeleteFailed,
  titleConfirm,
  titleSuccess,
  titleFailed,
  titlePersonal,
  titleTaskToday,
  titleFTF,
  titleMyTask,
  titleNotes,
  titleScope,
  titleMeetings,
  titleToday,
  titleThisWeek,
  titleHandlerRole,
  titlePleaseCheckIn,
  titleCheckIn,
  titleChooseStartTime,
  titleChooseExpectedEndTime,
  titleTaskList,
  titleSelectJobLevel,
  titleCheckOut,
  titleTask,
  titleMainTab,
  titleOverview,
  titleManager,
  titleHR,
  titleReport,
  titleOKR,
  titleSetUpStatusCheckIn,
  titleCheckIn2,
  titleTimeRecordOnShift,
  titleTimeRecordEndShift,
  titleExpectedEndTime,
  titleNoTaskToday,
  titleNoTaskPersonal,
  titleNoTaskTop,
  titleNoTaskAssign,
  titleNoTask,
  titleCreateSubtask,
  titleAddTaskToCheckIn,
  titleDeadline,
  titleUrgent,
  titleWorkingTime,
  titleResume,
  titleCheckOutVSub,
  titleBreakTimeVSub,
  titleResumeVSub,
  titleNoTaskCheckIn,
  titleTimeResume,
  titleTimeRecordBreakTime,
  titleTimeRecordResume,
  titleLink,
  titleNameTask,
  titleNoTaskInScope,
  titleSettingTask,
  titleDetailSubTask,
  titleEditSubTask,
  titleAddTaskToList,
  titleCreateNewTask,
  titleAddOldTask,
  titleChooseTask,
  titlePleaseChooseTask,
  titleCreateTaskPersonal,
  titleDocumentAndAnnounce,
  titleThanksForEffort,
  titleMainTask,
  titleMeeting,
  titleBackToPreviousPage,
  titleDoing,
  titleIssues,
  titleYour,
  titleSend,
  titleReceive,
  titleAll2,
  titleCreateIssue,
  titleChooseProject,
  titleSetting,
  titleAnonymous,
  titlePrivate,
  titlePublic,
  titleResponsible,
  titleTitle,
  titleNoResponse,
  titleYourIssues,
  titleType,
  titleTimeSend,
  titleReceiver,
  titleSender,
  titleProject,
  titleLevel,
  titleAttachments,
  titleSelectFile,
  titleAttachmentsFile,
  titleWorkHistory,
  titleDate,
  titleLogTime,
  titleWorkingPoint,
  titleNumOfTask,
  titleNumOfSubtask,
  titleSumBreak,
  titleTimeBreak,
  titleSendTo,
  titleFromStatus,
  titleToStatus,
  titleCapacityExceeded,
  titleComment,
  titleTaskDetail,
  titleListSubtask,
  titleListHr,
  titleListProject,
  titleList,
  titleProgressTask,
  titleListOkrs,
  titleListIssue,
  titleFileAttachments,
  titleFollowers,
  titleDuplicateNote,
  titleListMeetings,
  titleAddFileAttachment,
  titleAnnounce,
  titleChangeAvatar,
  titleIcon,
  titleEmoji,
  titleCheckList,
  titleEvaluation,
  titleProcedure,
  titleListEvaluations,
  titleDetailEvaluation,
  titleContentEvaluation,
  titleEnhanceEvaluation,
  titleImproveEvaluation,
  titleListChecklist,
  titleCreateChecklist,
  titleListChecklistTemplates,
  titleProcedureStaff,
  titleListProcedure,
  titleCreateProcedure,
  titleProcedureStatus,
  titleProcedureDetail,
  titleProcessPerson,
  titleMeetingDetails,
  titleLibraryQuote,
  titleShowYourQuote,
  titleDuplicateWorkingUnit,
  titleChooseParentDuplicateWU,
  titleOldStatus,
  titleNewStatus,
  titleTimeDoingTask,
  titleFunctionPage,
  titleMeetingToday,
  titleNoMeetingToday,

  textByDay,
  textSynthetic,
  textIntroduceLogin,
  textHasError,
  textFillForm,
  textLoginSuccessful,
  textWrongPassword,
  textCreateAccountSuccessful,
  textCreateAccountFailed,
  textWeakPassword,
  textEmailAlreadyUse,
  textEmailAddressInvalid,
  textSendNewPassword,
  textUserNotFound,
  textChangePasswordSuccessful,
  textChangePasswordFailed,
  textInAddUserMode,
  textUploadAvatar,
  textUploadAvatarDescription,
  textPersonalInformation,
  textMale,
  textFemale,
  textOther,
  textStaff,
  textDepartmentHead,
  textManager,
  textBoss,
  textTeamMarketing,
  textTeamHR,
  textTeamOther,
  textTeamIT,
  textTeamDesigns,
  textTeamSupports,
  textTeamSales,
  textTeamData,
  textPartTime,
  textFullTime,
  textIntern,
  textAdmin,
  textSubManager,
  textHandler,
  textTasker,
  textProbation,
  textPermanent,
  textDismissed,
  textResign,
  textFailProbation,
  textAddAccountSuccessful,
  textAddAccountFailed,
  textLackOfInformation,
  textPageNotFound,
  textOldPasswordNotCorrect,
  textNotFoundInformation,
  textUpdateUserSuccess,
  textUpdateUserFailed,
  textConfirmDelete,
  textDeleteSuccess,
  textDeleteFailed,
  textConfirmResetPassword,
  textResetPasswordSuccess,
  textResetPasswordFailed,
  textNotFoundAccount,
  textPasswordNotSame,
  textLoginFailed,
  textDone,
  textFixing,
  textPending,
  textWaiting,
  textCancelled,
  textFailed,
  textCompleted,
  textProcessing,
  textReworking,
  textRevising,
  textUnknown,
  textTop,
  textHigh,
  textNormal,
  textLow,
  textAll,
  textPleaseResume,
  textCheckInSuccess,
  textCheckInFailed,
  textChooseWork,
  textPleaseCheckTaskToday,
  textConfirmCheckOut,
  textCheckoutSuccess,
  textTaskPersonal,
  textTaskAssign,
  textConfirmLogout,
  textPrivateKey,
  textNoTaskToday,
  textNoTaskPersonal,
  textNoTaskTop,
  textNoTaskAssign,
  textNoTask,
  textTime,
  textEdit,
  textDelete,
  textAddTaskToCheckIn,
  textRemoveFromList,
  textCheckOut,
  textNoTaskCheckIn,
  textConfirmBreak,
  textResume,
  textDoneTaskToday,
  textCreateSubTaskDescription,
  textCreateNameForTask,
  textTaskDescription,
  textNoTaskInScope,
  textDetailSubTask,
  textEditSubTask,
  textConfirmDeleteTask,
  textNoTaskForCheckIn,
  textNoFindTask,
  textAddTaskToList,
  textChooseTask,
  textAddToTaskToday,
  textRemoveFromTaskToday,
  textCloseTask,
  textNone,
  textSubTaskShort,
  textViewMore,
  textNoTaskAll,
  textNoTaskAllDes,
  textThanksForEffort,
  textSubThanksForEffort,
  textNoDocAndAnnounce,
  textNoMeeting,
  textNoNote,
  textCantChooseRole,
  textStart,
  textCreateIssue1,
  textCreateIssue2,
  textIssueHigh,
  textIssueMedium,
  textIssueLow,
  textIssueCritical,
  textIssueUrgent,
  textIssueTrivial,
  textIssueBug,
  textIssueProblem,
  textIssueImprovement,
  textIssueConsideration,
  textIssueComplaint,
  textIssueProposal,
  textIssueFeedback,
  textIssueOther,
  textPleaseChooseScope,
  textHintIssueTitle,
  textHintIssueDescription,
  textCreateIssueSuccess,
  textProcessed,
  textSeen,
  textNew,
  textRemovedIssue,
  textNotFix,
  textHavent,
  textAllScopeIssue,
  textAllTypeIssue,
  textAllUserIssue,
  textAllModeIssue,
  textAllPriorityIssue,
  textNoFindData,
  textSubNoFindData,
  textNoData,
  textSubNoData,
  textBreakFromWork,
  textNotPay,
  text3Days,
  text5Days,
  text10Days,
  textLastWeek,
  textThisWeek,
  textLastMonth,
  textThisMonth,
  textNextMonth,
  textPersonalIssue,
  textUndeterminedIssue,
  textMissHandlerIssue,
  textSortedTaskToday,
  textSortedTaskDoing,
  textSortedTaskFTF,
  textSortedTaskUrgent,
  textSortedTaskPersonal,
  textSortedTaskAssign,
  textSortedSubtask,
  textSortedTask,
  txtSortedManagerEpic,
  txtSortedManagerSprint,
  txtSortedManagerStory,
  txtSortedManagerTask,
  textSortedNote,
  textSortedMeeting,
  textSortedProcess,
  textBreakTime,
  textHaventStartYet,
  textClose,
  textReOpen,
  textByWeek,
  textByMonth,
  textPeriod,
  textPickImage,
  textPickVideo,
  textPickFile,
  textSendComment,
  textEnterComment,
  textEditIssue,
  textRemoved,
  textQuickAddIssue,
  textCheckInNoTask,
  textTypeIssue,
  textDoToday,
  textRemoveFromToday,
  textByScope,
  textByFull,
  textByUnFinished,
  textByFinished,
  textDoItFully,
  textReply,
  textConfirmDeleteComment,
  textClosed,
  textOpened,
  textSearchTask,
  textBack,
  textByAssign,
  textByUnassign,
  textNeedToDo,
  text2Week,
  text3Week,
  text4Week,
  text5Week,
  text6Week,
  text7Week,
  text8Week,
  text9Week,
  text10Week,
  text11Week,
  text12Week,
  textNextWeek,
  textTaskFollowing,
  textRepeatUntil,
  textImportant,
  textNoData2,
  textPersonSharing,
  textCreateDuplicate,
  textAddSubNote,
  textHide,
  textShareToScope,
  textShareToPerson,
  textShareToProject,
  textSelectScope,
  textCreateMeeting,
  textDescriptionCreateMeeting,
  textChooseScopeMeeting,
  textChooseMemberMeeting,
  textOwnerMeeting,
  textTimeMeeting,
  textTimeReminderMeeting,
  textStatusMeetingNone,
  textStatusMeetingIsGoingOn,
  textStatusMeetingEnded,
  textStatusMeetingDone,
  textNeedPrepare,
  textMember,
  textStatusMeeting,
  textOwnerMeetingShort,
  textTimeStartMeeting,
  textMemberMeeting,
  textMeetingContent,
  textPrepareDocuments,
  textRecordMeetings,
  textDetailMeeting,
  textDuration,
  textTypingSectionTitle,
  textTypingSectionDescription,
  textTypingNeedToDo,
  textAddFileAttachmentDescription,
  textNameFileAttachment,
  textLinkAttachment,
  textFileAttachment,
  textHintTitleFileAttachment,
  textHintLinkFileAttachment,
  textPickFileInHere,
  textOwnerPreparationMeeting,
  textContent,
  textList,
  textHintTypingTitle,
  textHintTypingTitleProcess,
  textHintTypingContent,
  textHintTypingDescription,
  textConfirmChangeParentNote,
  textHintSearchByTitle,
  textChangeAvatar,
  textDescriptionChangeAvatar,
  textResultNone,
  textResultExcellent,
  textResultCompleted,
  textResultOnTime,
  textResultOverdue,
  textResultAheadOfSchedule,
  textResultFailed,
  textResultBad,
  textResult,
  textPleaseSelectTaskToCheckOut,
  textCloseTaskSuccess,
  textHour,
  textMinute,
  textStatusEvaluationGood,
  textStatusEvaluationFair,
  textStatusEvaluationAverage,
  textStatusEvaluationPoor,
  textStatusEvaluationUnstable,
  textStatusEvaluationUnstableShort,
  textHintTypingImproveEvaluation,
  textHintTypingEnhanceEvaluation,
  textHintTypingTitleEvaluationPoint,
  textHintTypingTitleDetailEvaluationPoint,
  textConfirmDeleteEvaluation,
  textDeleteEvaluationSuccessful,
  textSent,
  textNotSent,
  textHintTypingTitleChecklistTemplate,
  textHintTypingDescriptionChecklistTemplate,
  textHintTypingTitleChecklist,
  textHintTypingDescriptionChecklist,
  textContentChecklist,
  textTitleChecklist,
  textContentChecklistTemplate,
  textTitleChecklistTemplate,
  textHintSearchChecklistTemplate,
  textConfirmDeleteChecklistItem,
  textHintTitleProcedure,
  textHintDescriptionProcedure,
  textCanBeEdit,
  textCannotBeEdit,
  textProcessCheckbox,
  textProcessProgress,
  textProcessContent,
  textSelectType,
  textConfirmDeleteProcess,
  textEffective,
  textIneffective,
  textDelete2,
  textShowQuote,
  textQuoteLibrary,
  textCannotCreateSubtask,
  textSelectWorkingBeforeAssign,
  textNeedAddDescriptionToAddMember,
  textAllRole,
  textAllDepartment,
  textConfirmDeleteScope,
  textHintSearchQuote,
  textHintCreateQuote,
  textHintCreateCategoryQuote,
  textHintTypingAuthor,
  textConfirmDeleteQuote,
  textNoQuoteSelected,
  textTurnOffDuringDay,
  textTurnOnDuringDay,
  textTurnOnAutoNextQuote,
  textTurnOffAutoNextQuote,
  textGoToSettingQuotePage,
  textDuplicateWorkingUnit,
  textSelectPathDuplicateWorkingUnit,
  textDuplicateWU,
  textDoneAllSubTaskToEditDefault,
  textChooseTimeMeeting,
  textPleaseChooseTimeMeeting,
  textSumTimeDoingTask,
  textSumWorkingPoint,
  textPleaseCheckedAllToCheckout,
  textTomorrow,
  textNext3Days,
  textPleaseChooseTimeDoingTask,
  textLanguageCompiler,
  textNameColLesson,
  textNameColSentence,
  textNameColSrc,
  textListTargetLang,
  textSelectFileAttachment,
  textSelectAnotherFileAttachment,
  textColLessonEmpty,
  textColSentenceEmpty,
  textEmptyListTargetLang,
  textPleaseSelectFile,
  textDesMeetingToday,

  btnLogin,
  btnOk,
  btnAdd,
  btnCancel,
  btnCreate,
  btnDelete,
  btnAddStaff,
  btnFilterStaff,
  btnCreateAccount,
  btnChangPassword,
  btnEditInformation,
  btnDeleteAccount,
  btnUpdate,
  btnConfirm,
  btnResetPassword,
  btnOKRS,
  btnImprovementProblem,
  btnCheckIn,
  btnProfile,
  btnTask,
  btnBreak,
  btnResume,
  btnCheckOut,
  btnLogout,
  btnCreateTask,
  btnUpdateTask,
  btnReCheckIn,
  btnReportIssue,
  btnSendIssue,
  btnClose,
  btnCreateNote,
  btnCreateMeeting,
  btnUploadImage,
  btnAddEvaluation,
  btnCreateEvaluation,
  btnCreateChecklistTemplate,
  btnAddChecklistFromTemplate,
  btnSaveChecklistTemplate,
  btnSelectTemplates,
  btnSaveProcedure,
  btnExecute,

  toastHaveNotSelectedProcess,

  titleManagementRole,
  txtListStaff,
  btnAddScope,
  txtListScope,
  btnFilterWork,
  txtCreatingScopeRemind,
  hintInputScopeName,
  hintInputScopeDescription,
  btnAddMemberIntoScope,
  btnAddViewerIntoScope,
  txtMembersOfScope,
  txtViewersOfScope,
  txtCreatorScope,
  txtNoScope,
  btnAddSubScope,
  btnRemoveSubScope,
  txtChooseStaff,
  desChooseStaff,
  titleChooseStaff,
  titleChooseScope,
  titleChooseAssignment,
  btnCreateWorkUnit,
  btnCreateAssignment,
  txtListChildAssignment,
  titleCreateAssignment,
  titleDescription,
  titleStartDate,
  titleEndDate,
  titlePriorityLevel,
  titlePriorityLevelShort,
  titleAssigner,
  hintAddPeople,
  titleChooseTypeOfAssignment,
  titleAttachment,
  hintAddAttachment,
  hintInputNameAssignment,
  hintInputDescriptionAssignment,
  hintInputStartDate,
  hintInputEndDate,
  titleAssignee,
  titleMember,
  txtEpic,
  txtSprint,
  txtStory,
  txtTask,
  txtSubTask,
  txtPriorityTop,
  txtPriorityHigh,
  txtPriorityLow,
  txtPriorityNormal,
  titleErrorNotification,
  txtInvalidStartEndDate,
  txtInvalidUrgentDate,
  txtInvalidAssignee,
  txtWorkingPoint,
  txtPoint,
  btnBackHome,
  txtExecutionDate,
  txtDefaultNameSubTask,
  titleDocumentAndInstruction,
  titleEmptyDocument,
  txtEmptyDocument,
  titleAttachmentFile,
  titleEmptyAttachment,
  txtEmptyAttachment,
  txtListChildWorkingUnit,
  titleNotWorkingUnit,
  titleNotWorkingUnitInTab,
  txtNotWorkingUnit,
  titleSettingWorkingUnit,

  btnCreateOkrsGroup,

  idPersonalIssue,
  idUndeterminedIssue,

  titleCreator,
  toastNotEditStatus,
  toastNotCreator,
  toastLeastOne,
  titleProgress,
  btnCreateOKRsBiz,
  btnAddOKRs,
  titleCreateNewOKRs,
  txtCreateNewOKRs,
  titleChooseGroupOKRs,
  titleChooseOwnerOfOKRs,
  titleFrontPaper,
  titleGoal,
  titleMainResults,
  titleKR,
  hintFrontPaperOKRs,
  hintGoalOKRs,
  typeKRProgress,
  typeKRChecked,
  typeKRNumber,
  nameKRProgress,
  nameKRChecked,
  nameKRNumber,
  titleEmptyOKRs,
  txtEmptyOKRs,
  txtFailed,
  txtPartially,
  txtNotAchieved,
  txtCompleted,
  txtExceeded,
  txtKRTypeCompleted,
  hintInputNumber,
  headerRateProgress,
  headerRateTask,
  headerRateKR,
  headerWPs,
  headerTimes,
  headerOwner,
  toastAddKRs,
  toastNoPermissionChangeParent,
  toastInstructionDropTree,
  toastWarningParent,
  txtGroup,
}

Map<AppText, String> texts = {
  AppText.titleEcosystem: "Hệ sinh thái ",
  AppText.titleLoginSlogan: "Work & HR Management System",
  AppText.titleEmail: "Email",
  AppText.titlePassword: "Mật Khẩu",
  AppText.titleConfirmDelete: "Bạn có chắc chắn muốn xoá?",
  AppText.titleSearch: "Tìm kiếm",
  AppText.titleName: "Tên",
  AppText.titlePosition: "Chức vụ",
  AppText.titlePhone: "Số điện thoại",
  AppText.titleIdStaff: "Mã nhân viên",
  AppText.titleDepartments: "Phòng ban",
  AppText.titleGender: "Giới tính",
  AppText.titleCodeUser: "Mã nhân viên",
  AppText.titleBirthDay: "Ngày sinh",
  AppText.titleDetailedInformation: "Thông tin chi tiết",
  AppText.titleAddress: "Địa chỉ",
  AppText.titleMajor: "Trình độ chuyên môn",
  AppText.titleWorkType: "Hình thức làm việc",
  AppText.titleStatus: "Trạng thái",
  AppText.titleLeader: "Trưởng nhóm",
  AppText.titleOwner: "Người phụ trách",
  AppText.titleEmployeeInformation: "Thông tin nhân viên",
  AppText.titlePrivateInformation: "Thông tin bảo mật",
  AppText.titleNote: "Ghi chú",
  AppText.titlePrivateNote: "Ghi chú riêng tư",
  AppText.titleInternalAccount: "Tài khoản nội bộ",
  AppText.titleEmailLogin: "Email đăng nhập",
  AppText.titleRole: "Vai trò",
  AppText.titleAddAccount: "Đã tạo tài khoản",
  AppText.titleAddAccountFailed: "Tạo tài khoản thất bại",
  AppText.titleLackOfInformation: "Thiếu thông tin",
  AppText.titleChangePassword: "Đổi mật khẩu",
  AppText.titleOldPassword: "Mật khẩu cũ",
  AppText.titleNewPassword: "Mật khẩu mới",
  AppText.titleReEnterPassword: "Nhập lại mật khẩu mới",
  AppText.titleChangePasswordSuccess: "Đổi mật khẩu thành công",
  AppText.titleChangePasswordFailed: "Đổi mật khẩu thất bại",
  AppText.titleUserInformation: "Thông tin nhân viên",
  AppText.titleUpdateUserSuccess: "Cập nhật thành công",
  AppText.titleUpdateUserFailed: "Cập nhật thất bại",
  AppText.titleDeleteSuccess: "Xoá thành công",
  AppText.titleDeleteFailed: "Xoá thất bại",
  AppText.titleConfirm: "Xác nhận",
  AppText.titleSuccess: "Thành công",
  AppText.titleFailed: "Thất bại",
  AppText.titlePersonal: "Cá nhân",
  AppText.titleTaskToday: "Task hôm nay",
  AppText.titleFTF: "First thing first",
  AppText.titleMyTask: "My task",
  AppText.titleScope: "Phòng ban",
  AppText.titleMeetings: "Meeting",
  AppText.titleToday: "Hôm nay",
  AppText.titleThisWeek: "Tuần này",
  AppText.titleHandlerRole: "Handler Role",
  AppText.titlePleaseCheckIn: "Vui lòng check in trước để có thể làm việc",
  AppText.titleCheckIn: "Check in",
  AppText.titleChooseStartTime: "Giờ bắt đầu",
  AppText.titleChooseExpectedEndTime: "Kết thúc dự kiến ",
  AppText.titleTaskList: "Danh sách nhiệm vụ",
  AppText.titleSelectJobLevel: "Chọn lọc mức công việc ",
  AppText.titleCheckOut: "Check out",
  AppText.titleTask: "Nhiệm vụ",
  AppText.titleMainTab: "Trang chủ",
  AppText.titleOverview: "Tổng quan",
  AppText.titleManager: "Quản lý",
  AppText.titleHR: 'Nhân sự',
  AppText.titleReport: "Báo cáo",
  AppText.titleOKR: "OKRs",
  AppText.titleSetUpStatusCheckIn: "Cài đặt trạng thái vào ca",
  AppText.titleCheckIn2: "VÀO CA",
  AppText.titleTimeRecordOnShift: "Thời gian ghi nhận vô ca",
  AppText.titleExpectedEndTime: "Thời gian dự kiến kết thúc ca",
  AppText.titleNoTaskToday: "Chưa có nhiệm vụ hôm nay",
  AppText.titleNoTaskPersonal: "Chưa có nhiệm vụ cá nhân",
  AppText.titleNoTaskTop: "Chưa có nhiệm vụ làm liền",
  AppText.titleNoTaskAssign: "Chưa có nhiệm vụ được giao",
  AppText.titleNoTask: "Chưa có nhiệm vụ",
  AppText.titleCreateSubtask: "Tạo Subtask",
  AppText.titleAddTaskToCheckIn: "THÊM NHIỆM VỤ VÀO CA LÀM",
  AppText.titleDeadline: "Deadline",
  AppText.titleUrgent: "Gấp",
  AppText.titleWorkingTime: "Thời gian làm",
  AppText.titleResume: "Tiếp tục",
  AppText.titleCheckOutVSub: "Kết thúc ca",
  AppText.titleBreakTimeVSub: "Tạm nghỉ ca",
  AppText.titleTimeRecordEndShift: "Thời gian ghi nhận kết thúc ca",
  AppText.titleNoTaskCheckIn: "Danh sách nhiệm vụ của bạn đang trống",
  AppText.titleTimeResume: "Thời gian quay lại ca làm",
  AppText.titleTimeRecordBreakTime: "Thời gian ghi nhận bắt đầu nghỉ của bạn :",
  AppText.titleTimeRecordResume: "Thời gian ghi nhân bạn quay lại ca làm :",
  AppText.titleResumeVSub: "QUAY LẠI LÀM VIỆC",
  AppText.titleLink: "Liên kết",
  AppText.titleNameTask: "Tên nhiệm vụ",
  AppText.titleNoTaskInScope: "Bạn không có nhiệm vụ trong phòng ban này",
  AppText.titleSettingTask: "Cài đặt nhiệm vụ",
  AppText.titleDetailSubTask: "Chi tiết nhiệm vụ con",
  AppText.titleEditSubTask: "Chỉnh sửa nhiệm vụ con",
  AppText.titleAddTaskToList: "THÊM TASK VÀO DANH SÁCH",
  AppText.titleCreateNewTask: "Tạo task mới",
  AppText.titleAddOldTask: "Thêm task cũ",
  AppText.titleChooseTask: "CHỌN NHIỆM VỤ",
  AppText.titlePleaseChooseTask: "Vui lòng chọn một nhiệm vụ trước khi tạo",
  AppText.titleCreateTaskPersonal: "Tạo nhiệm vụ cá nhân",
  AppText.titleDocumentAndAnnounce: "Tài liệu và thông báo",
  AppText.titleThanksForEffort: "Cảm ơn vì đã nỗ lực",
  AppText.titleMainTask: "Nhiệm vụ chính",
  AppText.titleMeeting: "Lịch họp",
  AppText.titleBackToPreviousPage: "< Quay lại",
  AppText.titleDoing: "Đang làm",
  AppText.titleIssues: "Cải tiến",
  AppText.titleYour: "Của bạn",
  AppText.titleSend: "Gửi",
  AppText.titleReceive: "Nhận",
  AppText.titleAll2: "Toàn bộ",
  AppText.titleCreateIssue: "BÁO LỖI và GÓP Ý CẢI TIẾN",
  AppText.titleChooseProject: "Dự án bạn muốn chọn",
  AppText.titleSetting: "Cài đặt",
  AppText.titleAnonymous: "Ẩn danh",
  AppText.titlePrivate: "Riêng tư",
  AppText.titleResponsible: "Chịu trách nhiệm",
  AppText.titleTitle: "Tiêu đề",
  AppText.titleNoResponse: "Chưa phản hồi",
  AppText.titleYourIssues: "Các vấn đề của bạn",
  AppText.titleType: "Loại",
  AppText.titleTimeSend: "Ngày gửi",
  AppText.titleReceiver: "Người nhận",
  AppText.titleSender: "Người gửi",
  AppText.titleProject: "Dự án",
  AppText.titleLevel: "Mức độ",
  AppText.titlePublic: "Công khai",
  AppText.titleAttachments: "Đăng tải tệp đính kèm liên quan",
  AppText.titleSelectFile: "Chọn tệp đính kèm",
  AppText.titleAttachmentsFile: "Tệp đính kèm",
  AppText.titleWorkHistory: "Lịch sử làm việc",
  AppText.titleDate: "Ngày",
  AppText.titleLogTime: "Logtime",
  AppText.titleWorkingPoint: "Điểm hoạt động",
  AppText.titleNumOfTask: "Tổng nhiệm vụ",
  AppText.titleSumBreak: "Nghỉ ngơi",
  AppText.titleTimeBreak: "Thời gian ghi nhận bắt đầu nghỉ ngơi",
  AppText.titleNumOfSubtask: "Nhiệm vụ con",
  AppText.titleSendTo: "Gửi tới",
  AppText.titleFromStatus: "Trước",
  AppText.titleToStatus: "Sau",
  AppText.titleCapacityExceeded: "Vượt quá dung lượng",
  AppText.titleComment: "Bình luận",
  AppText.titleTaskDetail: "Chi tiết nhiệm vụ",
  AppText.titleListSubtask: "Danh sách nhiệm vụ con",
  AppText.titleListHr: "Danh sách nhân sự",
  AppText.titleListProject: "Danh sách dự án",
  AppText.titleList: "Danh sách",
  AppText.titleProgressTask: "Tiến trình nhiệm vụ",
  AppText.titleListOkrs: "Danh sách OKRS",
  AppText.titleListIssue: "Danh sách vấn đề",
  AppText.titleFileAttachments: "Tệp đính kèm",
  AppText.titleFollowers: "Người theo dõi",
  AppText.titleDuplicateNote: "Nhân đôi ghi chú",
  AppText.titleListMeetings: "Danh sách cuộc họp",
  AppText.titleAddFileAttachment: "Thêm tệp đính kèm",
  AppText.titlePriorityLevelShort: "Mức độ",
  AppText.titleAnnounce: "Thông báo",
  AppText.titleChangeAvatar: "Đổi ảnh đại diện",
  AppText.titleIcon: "Icon",
  AppText.titleEmoji: "Emoji",
  AppText.titleCheckList: "Checklist",
  AppText.titleEvaluation: "Đánh giá",
  AppText.titleProcedure: "Quy trình",
  AppText.titleListEvaluations: "Danh sách đánh giá",
  AppText.titleDetailEvaluation: "Chi tiết đánh giá",
  AppText.titleContentEvaluation: "Nội dung đánh giá",
  AppText.titleEnhanceEvaluation: "Cần phát huy",
  AppText.titleImproveEvaluation: "Cần cải thiện",
  AppText.titleListChecklist: "Danh sách Checklist",
  AppText.titleCreateChecklist: "Tạo mẫu Checklist",
  AppText.titleListChecklistTemplates: "Danh sách Checklist mẫu",
  AppText.titleProcedureStaff: "Quy Trình Nhân Viên",
  AppText.titleListProcedure: "Danh Sách Quy Trình",
  AppText.titleCreateProcedure: "Tạo quy trình",
  AppText.titleProcedureStatus: "Trang thái quy trình",
  AppText.titleProcedureDetail: "Chi Tiết Quy Trình",
  AppText.titleProcessPerson: "Người làm quy trình",
  AppText.titleMeetingDetails: "Chi tiết cuộc họp",
  AppText.titleLibraryQuote: "Danh mục bộ trích dẫn",
  AppText.titleShowYourQuote: "Hiển thị trích dẫn của bạn",
  AppText.titleDuplicateWorkingUnit: "Tạo bản sao @",
  AppText.titleChooseParentDuplicateWU: "Chọn đường dẫn bạn muốn nhân bản vào",
  AppText.titleOldStatus: "Trạng thái cũ",
  AppText.titleNewStatus: "Trạng thái mới",
  AppText.titleTimeDoingTask: "Thời gian làm hôm nay",
  AppText.titleFunctionPage: "Trang chức năng",
  AppText.titleMeetingToday: "Lịch họp hôm nay",
  AppText.titleNoMeetingToday: "Chưa tìm thấy cuộc họp nào trong hôm nay",

  AppText.textIntroduceLogin: "Work and HR Management System là nền tảng giúp doanh nghiệp quản lý công việc và nhân sự hiệu quả hơn, từ theo dõi tiến độ dự án, đến quản lý hồ sơ nhân viên và phân tích hiệu suất. Hệ thống mang đến sự minh bạch, chuyên nghiệp và hỗ trợ doanh nghiệp tối ưu hóa quy trình làm việc cũng như phát triển nguồn nhân lực bền vững.",
  AppText.textHasError: "Đã có lỗi xảy ra",
  AppText.textFillForm: "Vui lòng nhập đầy đủ thông tin",
  AppText.textLoginSuccessful: "Đăng nhập thành công",
  AppText.textWrongPassword: "Tài khoản hoặc mật khẩu không chính xác",
  AppText.textCreateAccountSuccessful: "Tài khoản được tạo thành công",
  AppText.textCreateAccountFailed: "Tạo tài khoản thất bại",
  AppText.textWeakPassword: "Mật khẩu quá yếu",
  AppText.textEmailAlreadyUse:
      "Email này đã được sử dụng cho một tài khoản khác",
  AppText.textEmailAddressInvalid: "Địa chỉ email không hợp lệ",
  AppText.textSendNewPassword: "Mật khẩu đặt lại đã được gửi đến ",
  AppText.textUserNotFound: "Không tìm thấy người dùng này",
  AppText.textChangePasswordSuccessful: "Đổi mật khẩu thành công",
  AppText.textChangePasswordFailed: "Đổi mật khẩu thất bại",
  AppText.textInAddUserMode: "Đang trong chế độ thêm nhân viên",
  AppText.textUploadAvatar: "Tải ảnh đại diện",
  AppText.textUploadAvatarDescription:
      "Avatar mặc định sẽ được áp dụng khi không có hình ảnh cá nhân chỉ định",
  AppText.textPersonalInformation: "Thông tin cá nhân",
  AppText.textMale: "Nam",
  AppText.textFemale: "Nữ",
  AppText.textOther: "Khác",
  AppText.textStaff: "Nhân viên",
  AppText.textDepartmentHead: "Trưởng phòng",
  AppText.textManager: "Quản lý",
  AppText.textBoss: "Sếp",
  AppText.textTeamMarketing: 'Marketing',
  AppText.textTeamHR: 'HR',
  AppText.textTeamOther: 'Khác',
  AppText.textTeamDesigns: "Design",
  AppText.textTeamIT: "IT",
  AppText.textTeamData: "Data",
  AppText.textTeamSales: "Sale",
  AppText.textTeamSupports: "Support",
  AppText.textPartTime: "Bán thời gian",
  AppText.textFullTime: "Toàn thời gian",
  AppText.textIntern: "Thực tập sinh",
  AppText.textAdmin: "Admin",
  AppText.textSubManager: "Phó phòng",
  AppText.textHandler: "Trưởng phòng",
  AppText.textTasker: "Nhân viên",
  AppText.textProbation: "Thử việc",
  AppText.textPermanent: "Chính thức",
  AppText.textDismissed: "Sa thải",
  AppText.textResign: "Tự nghỉ việc",
  AppText.textFailProbation: "Không đạt thử việc",
  AppText.textAddAccountSuccessful: "Đã tạo tài khoản thành công",
  AppText.textAddAccountFailed: "Đã thất bại trong việc tạo tài khoản",
  AppText.textLackOfInformation: "Vui lòng nhập đầy đủ thông tin để tiếp tục",
  AppText.textPageNotFound:
      "Trang không tồn tại hoặc bạn không đủ quyền hạn để truy cập",
  AppText.textOldPasswordNotCorrect: "Mật khẩu cũ không trùng khớp",
  AppText.textNotFoundInformation:
      "Không tìm thấy thông tin hoặc không có đủ quyền hạn truy cập",
  AppText.textUpdateUserSuccess: "Đã cập nhật thông tin nhân viên thành công",
  AppText.textUpdateUserFailed: "Gặp lỗi trong quá trình cập nhật nhân viên",
  AppText.textConfirmDelete: "Bạn có chắc chắn muốn thực hiện thao tác xoá này?",
  AppText.textDeleteSuccess: "Đã xoá thành công tài khoản này",
  AppText.textDeleteFailed: "Đã xảy ra lỗi trong quá trình xoá",
  AppText.textConfirmResetPassword:
      "Chắc chắn rằng bạn muốn đặt lại mật khẩu cho tài khoản này",
  AppText.textResetPasswordSuccess: "Mật khẩu đã được gửi đến: ",
  AppText.textResetPasswordFailed:
      "Đã gặp lỗi trong quá trình đặt lại mật khẩu",
  AppText.textNotFoundAccount: "Không tìm thấy tài khoản",
  AppText.textPasswordNotSame: "Mật khẩu nhập lại không trùng khớp",
  AppText.textLoginFailed: "Đăng nhập thất bại",
  AppText.textDone: "Đã xong",
  AppText.textFixing: "Đang sửa",
  AppText.textPending: "Tạm dừng",
  AppText.textWaiting: "Đang đợi",
  AppText.textCancelled: "Huỷ bỏ",
  AppText.textFailed: "Không hoàn thành",
  AppText.textCompleted: "Hoàn thành",
  AppText.textProcessing: "Đang làm",
  AppText.textReworking: "Đang sửa",
  AppText.textRevising: "Đang sửa lại",
  AppText.textUnknown: "Không rõ",
  AppText.textTop: "Rất gấp",
  AppText.textHigh: "Làm ngay",
  AppText.textNormal: "Bình thường",
  AppText.textLow: "Thấp",
  AppText.textAll: "Tất cả",
  AppText.textPleaseResume: "Vui lòng resume để tiếp tục làm việc",
  AppText.textCheckInSuccess:
      "Đã check in thành công, chúc bạn có một ngày làm việc thật tốt ^^",
  AppText.textCheckInFailed: "Check in thất bại, hãy thử lại",
  AppText.textChooseWork: "Vui lòng chọn công việc sẽ làm trong ngày hôm nay",
  AppText.textPleaseCheckTaskToday:
      "Bạn nhớ kiểm tra thanh trạng trái của các nhiệm vụ đã làm hoặc đang làm trong ngày hôm nay trước khi kết thúc công việc ngày hôm nay nhé ^^",
  AppText.textConfirmCheckOut: "Bạn có chắc chắn muốn check out?",
  AppText.textCheckoutSuccess:
      "Bạn đã hoàn thành rất tốt hôm nay. Hãy dành thời gian để nghỉ ngơi và tái tạo năng lượng nhé!",
  AppText.textTaskPersonal: "Cá nhân",
  AppText.textTaskAssign: "Được giao",
  AppText.textConfirmLogout: "Bạn có chắc chắn muốn đăng xuất",
  AppText.textPrivateKey: "-PhamNgocThinh22092004-",
  AppText.textNoTaskToday: "Hãy checkin đề được nhận task",
  AppText.textNoTaskPersonal:
      "Hiện tại, bạn chưa được giao nhiệm vụ cá nhân nào. Vui lòng kiểm tra lại sau hoặc đợi thông báo phân công mới.",
  AppText.textNoTaskTop:
      "Hiện tại, bạn không có nhiệm vụ nào cần ưu tiên thực hiện ngay.",
  AppText.textNoTaskAssign:
      "Hiện tại, bạn chưa được giao nhiệm vụ cụ thể nào. Vui lòng kiểm tra lại thông tin hoặc đợi các nhiệm vụ mới được phân công từ quản lý.",
  AppText.textNoTask: "",
  AppText.textTime: "Thời gian",
  AppText.textEdit: "Sửa",
  AppText.textDelete: "Xoá",
  AppText.textAddTaskToCheckIn: "Cài đặt trạng thái vào ca",
  AppText.textRemoveFromList: "Xóa",
  AppText.textCheckOut: "Cài đặt trạng thái kết thúc ca",
  AppText.textNoTaskCheckIn: "Hãy thêm danh sách nhiệm vụ của bạn",
  AppText.textConfirmBreak: "Bạn muốn nghỉ ngơi một chút đúng không?",
  AppText.textResume: "Bạn hãy bấm tiếp tục làm việc",
  AppText.textDoneTaskToday: "Bạn Đã Hoàn Thành Công Việc Hôm Nay\n Cám Ơn Vì Đã Nỗ Lực",
  AppText.textCreateSubTaskDescription: "Tạo subtask cho task hiện tại của bạn đang làm",
  AppText.textCreateNameForTask: "Đặt tên cho nhiệm vụ",
  AppText.textTaskDescription: "Mô tả nhiệm vụ",
  AppText.textNoTaskInScope: "Vui lòng đổi phòng ban khác hoặc đợi được phân nhiệm vụ vào phòng ban này",
  AppText.textDetailSubTask: "Chi tiết nhiệm vụ con của bạn",
  AppText.textEditSubTask: "Chỉnh sửa nhiệm vụ con cho nhiệm vụ của bạn",
  AppText.textConfirmDeleteTask: "Bạn có chắc chắn muốn xoá nhiệm vụ này",
  AppText.textNoTaskForCheckIn: "Không tìm thấy nhiệm vụ của bạn, cần tạo nhiệm vụ và nhiệm vụ con trước khi bấm vào ca",
  AppText.textNoFindTask: "Không tìm thấy nhiệm vụ của bạn",
  AppText.textAddTaskToList: "Bạn có thể tạo task mới hoặc tìm kiếm các task bạn đã làm",
  AppText.textChooseTask: "Chọn nhiệm vụ bạn muốn thêm nhiệm vụ con vào",
  AppText.textAddToTaskToday: "Thêm vào nhiệm vụ hôm nay",
  AppText.textRemoveFromTaskToday: "Xoá khỏi nhiệm vụ hôm nay",
  AppText.textCloseTask: "Đóng nhiệm vụ",
  AppText.textNone: "Mới",
  AppText.textSubTaskShort: "Tác vụ",
  AppText.textViewMore: "Xem thêm",
  AppText.textNoTaskAll: "Chúc bạn một ngày làm việc thuận lợi và tràn đầy cảm hứng.",
  AppText.textNoTaskAllDes: " Nếu cần sự hỗ trợ, đừng ngần ngại liên hệ với bộ phận IT hoặc quản lý. Mọi thành công đều bắt đầu từ những bước đi kiên định hôm nay.",
  AppText.textThanksForEffort: "Chúc mừng bạn đã hoàn thành công việc hôm nay",
  AppText.textSubThanksForEffort: "Xin trân trọng cảm ơn sự hợp tác và đóng góp của quý đồng nghiệp trong ngày làm việc hôm nay. Kính chúc mọi người có một buổi tối tốt lành, hẹn gặp lại vào ngày làm việc tiếp theo",
  AppText.textNoDocAndAnnounce: "Hiện tại chưa có tài liệu hoặc thông báo nào",
  AppText.textNoMeeting: "Hiện tại chưa có lịch họp nào",
  AppText.textNoNote: "Chưa có ghi chú nào",
  AppText.textCantChooseRole: "Bạn không đủ quyền hạn để cấp vai trò này cho người dùng",
  AppText.textStart: "Bắt đầu",
  AppText.textCreateIssue1: "Bạn có thể báo cáo vấn đề hoặc nêu các đề xuất để cải tiến cho bất kỳ sản phầm, phòng ban hay nhân sự nào trong toàn công ty, mọi đề xuất góp ý đều được khuyến khích, trân trọng và",
  AppText.textCreateIssue2: " mang ý nghĩa sống còn cho sự phát triển của công ty",
  AppText.textIssueCritical: "Nghiêm trọng",
  AppText.textIssueUrgent: "Cấp bách",
  AppText.textIssueTrivial: "Không cấp bách",
  AppText.textIssueHigh: "Cao",
  AppText.textIssueMedium: "Trung bình",
  AppText.textIssueLow: "Thấp",
  AppText.textIssueBug: "Báo lỗi",
  AppText.textIssueProblem: "Vấn đề",
  AppText.textIssueImprovement: "Cải tiến",
  AppText.textIssueConsideration: "Xem xét",
  AppText.textIssueComplaint: "Khiếu nại",
  AppText.textIssueProposal: "Đề xuất",
  AppText.textIssueFeedback: "Góp ý",
  AppText.textIssueOther: "Khác",
  AppText.textPleaseChooseScope: "Vui lòng chọn scope",
  AppText.textHintIssueDescription: "Mô tả vấn đề",
  AppText.textHintIssueTitle: "Đặt tiêu đề cho vấn đề này",
  AppText.textCreateIssueSuccess: "Đã gửi thành công",
  AppText.textProcessed: "Đã xử lý",
  AppText.textSeen: "Đã xem",
  AppText.textNew: "Mới",
  AppText.textRemovedIssue: "Đóng",
  AppText.textNotFix: "Không xử lý",
  AppText.textHavent: "Không có",
  AppText.textAllScopeIssue: "Tất cả phòng ban",
  AppText.textAllTypeIssue: "Tấ cả loại vấn đề",
  AppText.textAllUserIssue: "Tất cả người liên quan",
  AppText.textAllModeIssue: "Tất cả loại truy cập",
  AppText.textAllPriorityIssue: "Tất cả mức độ",
  AppText.textNoFindData: "Dữ liệu bạn đang tìm kiếm hiện không có",
  AppText.textSubNoFindData: "Có thể dữ liệu bạn tìm kiếm không tồn tại hoặc bạn không có đủ quyền truy cập",
  AppText.textBreakFromWork: "Nghỉ làm",
  AppText.textNotPay: "Coi như bỏ",
  AppText.text3Days: "3 ngày trước",
  AppText.text10Days: "10 ngày trước",
  AppText.textLastWeek: "Tuần trước",
  AppText.textThisWeek: "Tuần này",
  AppText.textThisMonth: "Tháng này",
  AppText.textLastMonth: "Tháng trước",
  AppText.textPersonalIssue: "Cá nhân",
  AppText.textUndeterminedIssue: "Không xác định",
  AppText.textMissHandlerIssue: "Lỗi gửi tới Cá Nhân phải chọn ít nhất 1 người nhận",
  AppText.textByDay: "Theo ngày",
  AppText.textSynthetic: "Tổng hợp",
  AppText.textSortedTaskToday: "task_today",
  AppText.textSortedTaskDoing: "task_doing",
  AppText.textSortedTaskFTF: "task_ftf",
  AppText.textSortedTaskUrgent: "task_urgent",
  AppText.textSortedTaskPersonal: "task_personal",
  AppText.textSortedTaskAssign: "task_assign",
  AppText.textSortedTask: "task",
  AppText.textSortedNote: "note",
  AppText.textSortedMeeting: "meeting",
  AppText.textSortedProcess: "process",
  AppText.textSortedSubtask: "subtask",
  AppText.textBreakTime: "Đang nghỉ ngơi",
  AppText.textHaventStartYet: "Chưa bắt đầu",
  AppText.textClose: "Đóng",
  AppText.textReOpen: "Mở lại",
  AppText.textByWeek: "Theo tuần",
  AppText.textByMonth: "Theo tháng",
  AppText.textPeriod: "Khoảng thời gian",
  AppText.textPickImage: "Đính kèm một ảnh",
  AppText.textPickVideo: "Đính kèm một video",
  AppText.textPickFile: "Đính kèm một tệp",
  AppText.textSendComment: "Gửi bình luận",
  AppText.textEnterComment: "Nhập bình luận...",
  AppText.text5Days: "5 Ngày trước",
  AppText.textEditIssue: "Chỉnh sửa",
  AppText.textRemoved: "Đã đóng",
  AppText.textQuickAddIssue: "Thêm nhanh vấn đề và cải tiến",
  AppText.textCheckInNoTask: "Checkin Nghiêm Túc Bằng Cách Lên Kế Hoạch Ngày",
  AppText.textNoData: "Chưa có",
  AppText.textTypeIssue: "Loại vấn đề",
  AppText.textDoToday: "Làm Hôm Nay",
  AppText.textRemoveFromToday: "Xoá Khỏi Hôm Nay",
  AppText.textByScope: "Theo phòng ban",
  AppText.textByFull: "Toàn bộ",
  AppText.textByUnFinished: "Chưa xong",
  AppText.textByFinished: "Đã xong",
  AppText.textDoItFully: "Làm đầy đủ",
  AppText.textReply: "Trả lời",
  AppText.textConfirmDeleteComment: "Bạn có chắc chắn muốn xoá bình luận này",
  AppText.textClosed: "Đã đóng",
  AppText.textOpened: "Đang mở",
  AppText.textSearchTask: "Tìm kiếm nhiệm vụ",
  AppText.textBack: "Quay lại",
  AppText.textByAssign: "Đã giao",
  AppText.textByUnassign: "Chưa giao",
  AppText.textNeedToDo: "Cần làm",
  AppText.text2Week: "2 Tuần",
  AppText.text3Week: "3 Tuần",
  AppText.text4Week: "4 Tuần",
  AppText.text5Week: "5 Tuần",
  AppText.text6Week: "6 Tuần",
  AppText.text7Week: "7 Tuần",
  AppText.text8Week: "8 Tuần",
  AppText.text9Week: "9 Tuần",
  AppText.text10Week: "10 Tuần",
  AppText.text11Week: "11 Tuần",
  AppText.text12Week: "12 Tuần",
  AppText.textNextWeek: "Tuần sau",
  AppText.textNextMonth: "Tháng sau",
  AppText.textTaskFollowing: "Đang theo dõi",
  AppText.textRepeatUntil: "Lặp lại đến",
  AppText.textImportant: "Quan trọng",
  AppText.textNoData2: "Không có dữ liệu",
  AppText.textPersonSharing: "Người được chia sẻ",
  AppText.textCreateDuplicate: "Tạo bản sao",
  AppText.textAddSubNote: "Thêm ghi chú phụ",
  AppText.textHide: "Ẩn",
  AppText.textShareToScope: "Chia sẻ cho phòng ban bạn chọn",
  AppText.textShareToProject: "Chia sẻ cho nhóm dự án bạn chọn",
  AppText.textShareToPerson: "Người bạn muốn chia sẻ là",
  AppText.textSelectScope: "Chọn phòng ban",
  AppText.textCreateMeeting: "Tạo mới cuộc họp",
  AppText.textDescriptionCreateMeeting: "",
  AppText.textChooseScopeMeeting: "Chọn phòng ban liên quan",
  AppText.textChooseMemberMeeting: "Chọn người tham dự",
  AppText.textOwnerMeeting: "Chủ trì cuộc họp",
  AppText.textTimeMeeting: "Thời gian họp",
  AppText.textTimeReminderMeeting: "Thời gian nhắc nhở",
  AppText.textStatusMeetingNone: "Mới",
  AppText.textStatusMeetingIsGoingOn: "Đang diễn ra",
  AppText.textStatusMeetingEnded: "Đã kết thúc",
  AppText.textStatusMeetingDone: "Đã xong",
  AppText.textNeedPrepare: "Cần chuẩn bị",
  AppText.textMember: "Thành viên",
  AppText.textStatusMeeting: "Trạng thái",
  AppText.textOwnerMeetingShort: "Chủ trì",
  AppText.textTimeStartMeeting: "Thời gian họp",
  AppText.textMemberMeeting: "Người tham dự họp",
  AppText.textMeetingContent: "Nội dung cuộc họp",
  AppText.textPrepareDocuments: "Chuẩn bị tài liệu",
  AppText.textRecordMeetings: "Biên bản cuộc họp",
  AppText.textDetailMeeting: "Chi tiết cuộc họp",
  AppText.textDuration: "Thời lượng",
  AppText.textTypingSectionTitle: "Nhập đề mục",
  AppText.textTypingSectionDescription: "Nhập mô tả đề mục",
  AppText.textTypingNeedToDo: "Điển việc cần làm vào đây",
  AppText.textAddFileAttachmentDescription: "File đính kèm hỗ trợ trong quá trình làm việc",
  AppText.textNameFileAttachment: "Tên tệp đính kèm",
  AppText.textFileAttachment: "Tệp đính kèm",
  AppText.textLinkAttachment: "Link đính kèm",
  AppText.textHintTitleFileAttachment: "Nhập tên tệp đính kèm",
  AppText.textHintLinkFileAttachment: "Nhập đường dẫn vào đây",
  AppText.textPickFileInHere: "Chọn tệp ở đây",
  AppText.textOwnerPreparationMeeting: "Người sở hữu",
  AppText.textContent: "Nội dung",
  AppText.textList: "Danh sách",
  AppText.textHintTypingTitle: "Nhập tiêu đề",
  AppText.textHintTypingContent: "Nhập nội dung",
  AppText.textHintTypingDescription: "Nhập mô tả",
  AppText.textConfirmChangeParentNote: "Bạn có chắc chắn muốn đổi cha của ghi chú này",
  AppText.textHintSearchByTitle: "Tìm kiếm theo tiêu đề",
  AppText.textChangeAvatar: "Bạn cần thay đổi avatar để tương tác thuận tiện hơn trong hệ thống",
  AppText.textDescriptionChangeAvatar: "Hình đại diện yêu cầu là hình có mặt người\nKhuyến nghị nên sử dụng ảnh hình vuông",
  AppText.textResultNone: "Không",
  AppText.textResultExcellent: "Xuất sắc",
  AppText.textResultCompleted: "Tốt",
  AppText.textResultOnTime: "Tạm",
  AppText.textResultOverdue: "Tệ",
  AppText.textResultAheadOfSchedule: "Ổn",
  AppText.textResultFailed: "Thất bại",
  AppText.textResultBad: "Tệ",
  AppText.textResult: "Kết quả",
  AppText.textPleaseSelectTaskToCheckOut: "Vui lòng chọn nhiệm vụ đã làm hôm nay để checkout",
  AppText.textCloseTaskSuccess: "Nhiệm vụ đã được đóng thành công\nBạn có thể mở lại nhiệm vụ ở Tab \"Nhiệm vụ\"",
  AppText.textHour: "giờ",
  AppText.textMinute: "phút",
  AppText.textStatusEvaluationGood: "Tốt",
  AppText.textStatusEvaluationFair: "Được",
  AppText.textStatusEvaluationAverage: "Tạm",
  AppText.textStatusEvaluationPoor: "Kém",
  AppText.textStatusEvaluationUnstable: "Không ổn",
  AppText.textStatusEvaluationUnstableShort: "Tệ",
  AppText.textHintTypingEnhanceEvaluation: "Điền việc cần phát huy vào đây",
  AppText.textHintTypingImproveEvaluation: "Điền việc cần cải thiện vào đây",
  AppText.textHintTypingTitleEvaluationPoint: "Nhập tiêu đề đánh giá ở đây",
  AppText.textHintTypingTitleDetailEvaluationPoint: "Nhập chi tiết đánh giá ở đây",
  AppText.textConfirmDeleteEvaluation: "Bạn có chắc chắn muốn xóa đánh giá này",
  AppText.textDeleteEvaluationSuccessful: "Đã xoá đánh giá thành công",
  AppText.textSent: "Đã gửi",
  AppText.textNotSent: "Chưa gửi",
  AppText.textHintTypingTitleChecklistTemplate: "Đặt tiêu đề cho mẫu checklist này",
  AppText.textHintTypingDescriptionChecklistTemplate: "Mô tả mẫu checklist",
  AppText.textHintTypingTitleChecklist: "Nhập tiêu đề cho checklist",
  AppText.textHintTypingDescriptionChecklist: "Nhập nội dung checklist",
  AppText.textContentChecklist: "Nội dung Checklist",
  AppText.textTitleChecklist: "Tiêu đề Checklist",
  AppText.textContentChecklistTemplate: "Nội dung mẫu Checklist",
  AppText.textTitleChecklistTemplate: "Tiêu đề mẫu Checklist",
  AppText.textHintSearchChecklistTemplate: "Nhập từ khoá để tìm kiếm",
  AppText.textConfirmDeleteChecklistItem: "Bạn có chắc chắn muốn xoá checklist này",
  AppText.textHintTitleProcedure: "Đặt tiêu đề cho quy trình này",
  AppText.textHintDescriptionProcedure: "Mô tả cho quy trình này",
  AppText.textCanBeEdit: "Có thể sửa",
  AppText.textCannotBeEdit: "Không thể sửa",
  AppText.textHintTypingTitleProcess: "Tiêu đề quy trình",
  AppText.textProcessCheckbox: "Hộp kiểm",
  AppText.textProcessContent: "Nội dung",
  AppText.textProcessProgress: "Tiến độ",
  AppText.textSelectType: "Chọn loại",
  AppText.textConfirmDeleteProcess: "Bạn có chắc chắn muốn xoá quy trình này",
  AppText.textDelete2: "Xoá bỏ",
  AppText.textEffective: "Có hiệu lực",
  AppText.textIneffective: "Không hiệu lực",
  AppText.textShowQuote: "Hiển Thị Trích Dẫn",
  AppText.textQuoteLibrary: "Thư Viện Trích Dẫn",
  AppText.textCannotCreateSubtask: "Không thể tạo nhiệm vụ con khi đã hoàn thành nhiệm vụ \"Review và bàn giao kết quả\"\nĐể có thể tạo nhiệm vụ con mới vui lòng đổi trạng thái nhiệm vụ \"Review và bàn giao kết quả\"",
  AppText.textSelectWorkingBeforeAssign: "Bạn phải ước lượng khối lượng công việc trước khi giao nhiệm vụ!!!",
  AppText.textNeedAddDescriptionToAddMember: "Cần lên chi tiết nội dung cuộc họp trước khi thêm người tham gia!!!!",
  AppText.textAllRole: "Tất cả chức vụ",
  AppText.textAllDepartment: "Tất cả phòng ban",
  AppText.textConfirmDeleteScope: "Bạn có chắc chắn muốn xoá phòng ban \"@\"",
  AppText.textHintSearchQuote: "Tìm kiếm câu trích dẫn hoặc trích dẫn của nhân viên",
  AppText.textHintCreateQuote: "Nhập trích dẫn mới của bạn vào đây",
  AppText.textHintTypingAuthor: "Nhập tên tác giả ở đây",
  AppText.textConfirmDeleteQuote: "Bạn có chắc chắn muốn xoá trích dẫn này?\n(Thấy cũng ổn mà ._.)",
  AppText.textNoQuoteSelected: "Chưa có câu trích dẫn nào được chọn",
  AppText.textTurnOffDuringDay: "Tắt đi trong hôm nay",
  AppText.textTurnOnDuringDay: "Bật lại trong hôm nay",
  AppText.textTurnOnAutoNextQuote: "Bật từ động chuyển câu",
  AppText.textTurnOffAutoNextQuote: "Tắt từ động chuyển câu",
  AppText.textGoToSettingQuotePage: "Đi tới trang cài đặt",
  AppText.textHintCreateCategoryQuote: "Nhập tên đề mục",
  AppText.textDuplicateWorkingUnit: "Nhân đôi theo cách của bạn",
  AppText.textSelectPathDuplicateWorkingUnit: "Chọn đường dẫn bạn muốn đặt vào",
  AppText.textDuplicateWU: "Nhân bản",
  AppText.textDoneAllSubTaskToEditDefault: "Vui lòng hoàn thành tất cả nhiệm vụ khác để có thể sửa nhiệm vụ review này",
  AppText.textChooseTimeMeeting: "Chọn thời gian",
  AppText.textPleaseChooseTimeMeeting: "Vui lòng chọn thời gian họp",
  AppText.textSumTimeDoingTask: "Tổng thời gian làm task",
  AppText.textSumWorkingPoint: "Tổng khối lượng công việc",
  AppText.textPleaseCheckedAllToCheckout: "Vui lòng xác nhận các thông tin trên để checkout",
  AppText.textTomorrow: "Ngày mai",
  AppText.textNext3Days: "3 ngày tới",
  AppText.textPleaseChooseTimeDoingTask: "Vui lòng chọn khoảng thời gian làm cho từng nhiệm vụ đã làm hôm nay",
  AppText.textLanguageCompiler: "Trình biên dịch",
  AppText.textNameColLesson:    "Cột bài học          ",
  AppText.textNameColSentence:  "Cột nội dung câu",
  AppText.textNameColSrc:       "Ngôn ngữ gốc     ",
  AppText.textListTargetLang:   "Danh sách ngôn ngữ đích",
  AppText.textSelectFileAttachment: "Chọn tệp đính kèm",
  AppText.textSelectAnotherFileAttachment: "Chọn tệp đính kèm khác",
  AppText.textColLessonEmpty: "Vui lòng không để trống cột bài học",
  AppText.textColSentenceEmpty: "Vui lòng không để trống cột nội dung",
  AppText.textEmptyListTargetLang: "Vui lòng chọn ít nhất 1 ngôn ngữ đích",
  AppText.textPleaseSelectFile: "Vui lòng chọn tệp",
  AppText.textDesMeetingToday: "Lịch họp hôm nay đã sẵn sàng! Nhớ check kỹ thời gian và nội dung để chuẩn bị tốt nhất. Cùng nhau phối hợp cho hiệu quả hơn nhé!",

  AppText.btnLogin: "Đăng nhập",
  AppText.btnChangPassword: "Đổi mật khẩu",
  AppText.btnEditInformation: "Chỉnh sửa thông tin",
  AppText.btnDeleteAccount: "Xóa tài khoản",
  AppText.btnUpdate: "Cập nhật",
  AppText.btnConfirm: "Xác nhận",
  AppText.btnResetPassword: "Đặt lại mật khẩu",
  AppText.btnOKRS: "OKRS",
  AppText.btnImprovementProblem: "Vấn đề về cải tiến",
  AppText.btnCheckIn: "Check in",
  AppText.btnProfile: "Profile",
  AppText.btnTask: "Nhiệm vụ",
  AppText.btnBreak: "Tạm nghỉ",
  AppText.btnResume: "Tiếp tục làm việc",
  AppText.btnCheckOut: "Check Out",
  AppText.btnLogout: "Đăng xuất",
  AppText.titleManagementRole: 'Management Role',
  AppText.txtListScope: 'Phòng ban',
  AppText.txtListStaff: 'Danh sách nhân viên',
  AppText.btnOk: "Ok",
  AppText.btnAdd: "Thêm vào",
  AppText.btnCancel: "Huỷ bỏ",
  AppText.btnCreate: "Tạo",
  AppText.btnDelete: "Xoá",
  AppText.btnAddStaff: "Thêm nhân viên",
  AppText.btnAddScope: "Tạo phòng ban",
  AppText.btnFilterStaff: "Filter User",
  AppText.btnFilterWork: "Filter Work",
  AppText.btnCreateTask: "Tạo nhiệm vụ",
  AppText.btnUpdateTask: "Cập nhật",
  AppText.btnReCheckIn: "Mở lại ca",
  AppText.btnReportIssue: "Báo Lỗi và Góp Ý Cải Tiến",
  AppText.btnSendIssue: "Gửi báo cáo",
  AppText.btnClose: "Đóng",
  AppText.btnCreateNote: "+ Tạo note",
  AppText.btnCreateMeeting: "Thêm cuộc họp",
  AppText.btnUploadImage: "Tải ảnh lên",
  AppText.btnAddEvaluation: "+ Đánh giá",
  AppText.btnCreateEvaluation: "Tạo đánh giá",
  AppText.btnCreateChecklistTemplate: "Tạo mẫu",
  AppText.btnAddChecklistFromTemplate: "Thêm từ mẫu",
  AppText.btnSaveChecklistTemplate: "Lưu mẫu",
  AppText.btnSelectTemplates: "Chọn mẫu",
  AppText.btnSaveProcedure: "Lưu quy trình",
  AppText.btnExecute: "Thực thi",

  AppText.toastHaveNotSelectedProcess: "Bạn chưa chọn bất kỳ quy trình nào",

  AppText.txtCreatingScopeRemind: 'Đang trong chế độ tạo phòng ban',
  AppText.txtMembersOfScope: 'Thành viên scope',
  AppText.txtViewersOfScope: 'Người theo dõi',
  AppText.txtCreatorScope: 'Được tạo bởi',
  AppText.txtNoScope: 'Hiện tại chưa có nhóm làm việc nào cả',
  AppText.btnAddSubScope: 'Thêm sub scope',
  AppText.btnAddMemberIntoScope: 'Thêm thành viên vào scope',
  AppText.btnAddViewerIntoScope: 'Thêm người theo dõi',
  AppText.hintInputScopeName: 'Nhập tên @ vào đây',
  AppText.hintInputScopeDescription: 'Nhập mô tả vào đây',
  AppText.btnCreateAccount: "Thêm tài khoản",
  AppText.btnRemoveSubScope: 'Xoá sub_scope',
  AppText.titleChooseStaff: 'Chọn nhân viên',
  AppText.txtChooseStaff: 'Chọn nhân viên tham gia vào phòng ban',
  AppText.desChooseStaff:
      'phòng ban của bạn  sẽ bao gồm những thành viên tham gia có thể ở những phòng ban khác nhau',
  AppText.titleChooseScope: 'Chọn phòng ban',
  AppText.titleChooseAssignment: 'Chọn nhiệm vụ cần làm',
  AppText.btnCreateWorkUnit: 'Tạo hạng mục công việc',
  AppText.btnCreateAssignment: 'Tạo @',
  AppText.txtListChildAssignment: 'Danh sách nhiệm vụ con',
  AppText.titleCreateAssignment: 'Bảng thiết lập hạng mục công việc',
  AppText.titleDescription: 'Mô tả',
  AppText.titleStartDate: 'Ngày bắt đầu',
  AppText.titleEndDate: 'Ngày kết thúc',
  AppText.titlePriorityLevel: 'Độ ưu tiên',
  AppText.titleAssigner: 'Phụ trách',
  AppText.hintAddPeople: 'Thêm người ở đây',
  AppText.titleChooseTypeOfAssignment: 'Chọn hạng mục công việc',
  AppText.titleAttachment: 'Tài liệu đính kèm',
  AppText.hintAddAttachment: 'Thêm tài liệu ở đây',
  AppText.hintInputNameAssignment: 'Tên của @',
  AppText.hintInputDescriptionAssignment: 'Mô tả @',
  AppText.hintInputStartDate: 'Khi nào nhiệm vụ bắt đầu',
  AppText.hintInputEndDate: 'Khi nào nhiệm vụ kết thúc',
  AppText.titleAssignee: 'Người làm task',
  AppText.titleMember: "Thành viên",
  AppText.txtEpic: 'Dự án',
  AppText.txtSprint: 'Giai đoạn',
  AppText.txtStory: 'Nhóm nhiệm vụ',
  AppText.txtTask: 'Nhiệm vụ',
  AppText.txtSubTask: "Nhiệm vụ con",
  AppText.txtPriorityTop: 'First Things First',
  AppText.txtPriorityHigh: 'Ưu tiên cao',
  AppText.txtPriorityLow: 'Ưu tiên thấp',
  AppText.txtPriorityNormal: 'Bình thường',
  AppText.titleErrorNotification: 'Thông báo lỗi',
  AppText.txtInvalidStartEndDate:
      'Vui lòng chọn ngày kết thúc sau ngày bắt đầu',
  AppText.txtInvalidUrgentDate: 'Vui lòng chọn ngày thực hiện trong khoảng ngày bắt đầu và ngày kết thúc',
  AppText.txtInvalidAssignee: 'Vui lòng chọn người làm nhiệm vụ',
  AppText.txtWorkingPoint: 'Khối lượng',
  AppText.txtPoint: 'điểm',
  AppText.btnBackHome: 'Quay lại trang chủ',
  AppText.txtExecutionDate: 'Ngày thực hiện',
  AppText.txtDefaultNameSubTask: 'Review và bàn giao kết quả',
  AppText.titleEmptyDocument: 'Danh sách tài liệu và hướng dẫn đang trống',
  AppText.txtEmptyDocument: 'Nếu cảm thấy cần thiết, xin vui lòng cung cấp thêm tài liệu và hướng dẫn để hỗ trợ tốt hơn.',
  AppText.titleEmptyAttachment: 'Danh sách đính kèm đang trống',
  AppText.txtEmptyAttachment: 'Nếu cảm thấy cần thiết, xin vui lòng cung cấp thêm đính kèm để hỗ trợ tốt hơn.',
  AppText.titleDocumentAndInstruction: 'Tài liệu và hướng dẫn',
  AppText.titleAttachmentFile: 'File đính kèm',
  AppText.txtListChildWorkingUnit: 'Danh sách hạng mục công việc con',
  AppText.titleNotWorkingUnit: 'Chưa có hạng mục công việc nào',
  AppText.titleNotWorkingUnitInTab: 'Chưa có @ nào',
  AppText.txtNotWorkingUnit: 'Hãy tạo hạng mục công việc',
  AppText.titleSettingWorkingUnit: 'Cài đặt @',

  AppText.btnCreateOkrsGroup: 'Tạo nhóm Okrs',
  AppText.idPersonalIssue: "idPersonalIssue - id này mà trùng thì em chịu thua",
  AppText.idUndeterminedIssue: "idUndeterminedIssue - id này mà trùng thì em chịu thua",
  AppText.titleCreator: "Người tạo",
  AppText.toastNotEditStatus: 'Bạn không thể chỉnh sửa, trạng thái sẽ được tự động cập nhật',
  AppText.toastNotCreator: 'Chỉ người tạo mới có quyền chỉnh sửa',
  AppText.toastLeastOne: 'Phải có ít nhất 1 @',
  AppText.titleProgress: 'Tiến độ',
  AppText.btnCreateOKRsBiz: 'Tạo OKRs công việc',
  AppText.btnAddOKRs: 'Thêm OKRs',
  AppText.titleCreateNewOKRs: 'Tạo mới OKRs',
  AppText.txtCreateNewOKRs: 'Bạn có thể tạo task mới OKRs ở đây',
  AppText.titleChooseGroupOKRs: 'Chọn nhóm OKRs',
  AppText.titleChooseOwnerOfOKRs: 'Chọn sở hữu OKRs',
  AppText.titleFrontPaper: 'Tiêu đề',
  AppText.titleGoal: 'Mục tiêu',
  AppText.titleMainResults: 'Kết quả chính',
  AppText.titleKR: 'KR@',
  AppText.hintFrontPaperOKRs: 'Đặt tên tiêu đề cho OKRs này',
  AppText.hintGoalOKRs: 'Đặt mục tiêu cho OKRs này',
  AppText.typeKRProgress: 'progress',
  AppText.typeKRChecked: 'checked',
  AppText.typeKRNumber: 'number',
  AppText.nameKRProgress: 'Tỉ lệ',
  AppText.nameKRChecked: 'Hoàn thành',
  AppText.nameKRNumber: 'Số lượng',
  AppText.titleEmptyOKRs: 'Chưa có OKRS được tạo',
  AppText.txtEmptyOKRs: 'Xin vui lòng xây dựng và thiết lập bộ OKRs chi tiết để định hướng các mục tiêu và kết quả then chốt cho đội ngũ, giúp theo dõi và đánh giá hiệu quả công việc trong giai đoạn tiếp theo.',
  AppText.txtPartially: 'Một phần',
  AppText.txtNotAchieved: 'Không đạt',
  AppText.txtCompleted: 'Hoàn thành',
  AppText.txtExceeded: 'Vượt mong đợi',
  AppText.txtKRTypeCompleted: '@ hoàn thành',
  AppText.hintInputNumber: 'Nhập số',
  AppText.txtSortedManagerEpic: 'manager_epic',
  AppText.txtSortedManagerSprint: 'manager_sprint',
  AppText.txtSortedManagerStory: 'manager_story',
  AppText.txtSortedManagerTask: 'manager_task',
  AppText.headerRateProgress: 'Progress trung bình KR %',
  AppText.headerRateTask: 'Số task',
  AppText.headerRateKR: 'KR',
  AppText.headerWPs: 'Khối lượng (điểm)',
  AppText.headerTimes: 'Thời gian',
  AppText.headerOwner: 'Sở hữu',
  AppText.toastAddKRs: 'Key result đang rỗng',
  AppText.toastNoPermissionChangeParent: 'Chỉ được phép đổi cha của "@"',
  AppText.toastInstructionDropTree: 'Hãy thả chuột khi viền màu đỏ xuất hiện',
  AppText.toastWarningParent: '@ không thể là con của #',
  AppText.txtGroup: 'Nhóm'
};

extension AppTexts on AppText {
  static String getStringValue(String value) {
    return value;
  }

  String get text => texts[this] ?? '--TextNotFound--';
}
